// Actions
export const FETCH_QUOTES = 'FETCH_QUOTES';
export const ADD_QUOTE = 'ADD_QUOTE';
export const FETCH_QUOTES_REQUEST = 'FETCH_QUOTES_REQUEST';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const ADD_QUOTE_REQUEST = 'ADD_QUOTE_REQUEST';