// Actions
export const FETCH_QUOTES = 'FETCH_QUOTES';
export const ADD_QUOTE = 'ADD_QUOTE';
export const FETCH_QUOTES_REQUEST = 'FETCH_QUOTES_REQUEST';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const ADD_QUOTE_REQUEST = 'ADD_QUOTE_REQUEST';

export const SAVE_ANNOTATION_REQUEST = 'SAVE_ANNOTATION_REQUEST';
export const SAVE_ANNOTATION_SUCCESS = 'SAVE_ANNOTATION_SUCCESS';
export const SAVE_ANNOTATION_FAILURE = 'SAVE_ANNOTATION_FAILURE';
export const FETCH_ANNOTATIONS_REQUEST = 'FETCH_ANNOTATIONS_REQUEST';

export const FETCH_ANNOTATIONS_SUCCESS = 'FETCH_ANNOTATIONS_SUCCESS';
export const FETCH_ANNOTATIONS_FAILURE = 'FETCH_ANNOTATIONS_FAILURE';