// actionTypes.js
export const FETCH_CLIENT_INFORMATION_START = 'FETCH_CLIENT_INFORMATION_START';
export const FETCH_CLIENT_INFORMATION_SUCCESS = 'FETCH_CLIENT_INFORMATION_SUCCESS';
export const FETCH_CLIENT_INFORMATION_FAILURE = 'FETCH_CLIENT_INFORMATION_FAILURE';

export const DELETE_CLIENT_INFORMATION_START = 'DELETE_CLIENT_INFORMATION_START';
export const DELETE_CLIENT_INFORMATION_SUCCESS = 'DELETE_CLIENT_INFORMATION_SUCCESS';
export const DELETE_CLIENT_INFORMATION_FAILURE = 'DELETE_CLIENT_INFORMATION_FAILURE';

export const EDIT_CLIENT_INFORMATION_START = 'EDIT_CLIENT_INFORMATION_START';
export const EDIT_CLIENT_INFORMATION_SUCCESS = 'EDIT_CLIENT_INFORMATION_SUCCESS';
export const EDIT_CLIENT_INFORMATION_FAILURE = 'EDIT_CLIENT_INFORMATION_FAILURE';

export const SUBMIT_INFORMATION = 'SUBMIT_INFORMATION';
export const SUBMIT_INFORMATION_SUCCESS = 'SUBMIT_INFORMATION_SUCCESS';
export const SUBMIT_INFORMATION_FAILURE = 'SUBMIT_INFORMATION_FAILURE';
