// ActionTypes.js
export const UPLOAD_TEXT_REQUEST = 'UPLOAD_TEXT_REQUEST';
export const UPLOAD_TEXT_SUCCESS = 'UPLOAD_TEXT_SUCCESS';
export const UPLOAD_TEXT_FAILURE = 'UPLOAD_TEXT_FAILURE';

// In actions/types.js or directly in your actions file
export const SET_USER_DETAILS = 'SET_USER_DETAILS';

// actionTypes.js
export const FETCH_PROFILES_START = 'FETCH_PROFILES_START';
export const FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS';
export const FETCH_PROFILES_FAILURE = 'FETCH_PROFILES_FAILURE';

export const FETCH_VENDORPROFILES_REQUEST = 'FETCH_VENDORPROFILES_REQUEST';
export const FETCH_VENDORPROFILES_SUCCESS = 'FETCH_VENDORPROFILES_SUCCESS';
export const FETCH_VENDORPROFILES_FAILURE = 'FETCH_VENDORPROFILES_FAILURE';

export const FETCH_API_DATA_REQUEST = 'FETCH_API_DATA_REQUEST';
export const FETCH_API_DATA_SUCCESS = 'FETCH_API_DATA_SUCCESS';
export const FETCH_API_DATA_FAILURE = 'FETCH_API_DATA_FAILURE';

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';
