export const CREATE_PROJECT_GROUP = 'CREATE_PROJECT_GROUP';
export const READ_PROJECT_GROUP = 'READ_PROJECT_GROUP'

export const READ_PROJECT_GROUP_BY_ID = 'READ_PROJECT_GROUP_BY_ID'
export const READ_PROJECT_GROUP_SUCCESS = 'READ_PROJECT_GROUP_SUCCESS';
export const UPDATE_PROJECT_GROUP = 'UPDATE_PROJECT_GROUP';
export const DELETE_PROJECT_GROUP = 'DELETE_PROJECT_GROUP';
export const PROJECT_GROUP_SUCCESS = 'PROJECT_GROUP_SUCCESS';


export const PROJECT_GROUP_FAILURE = 'PROJECT_GROUP_FAILURE';

export const FETCH_ALL_PROJECT_GROUPS = 'FETCH_ALL_PROJECT_GROUPS';
